[tool.black]
line-length = 100
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  | migrations
  | .venv
  | venv
)/
'''

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
ignore_missing_imports = true
exclude = [
    "migrations",
    ".venv",
    "venv",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "WorkoutTracker.settings"
